### ISSUE TITLE
PI_NC_Drill.drl file is not included in analog-pi/pi/Design/Gerber/  folder

### ISSUE THREAD

**Issue by JackRoten** [JQIamo/analog-pi#1]
I am building the PI Lockbox, currently I am in the stages of building the PCBs with a PCB company. There is one file that looks like it is missing from the pi/Design/Gerber/  folder that we will need to fully build these PCBs. LayerMap.txt lists PI_NC_Drill.drl as a file for the PI PCB, but it seems to be missing from the Gerber folder.

**Comment by restelli** [comment]
@JackRoten thanks for signaling the problem: there must have clearly been issues during the generation of the artwork files. I will look into the issue and get back on this as soon as possible. In the mean time please put the PCB fabrication in hold.

**Comment by restelli** [comment]
I believe that the gerber file for fabrication are in the "fab" directory therefore they should be found here: 
analog-pi/fab/pi_v2.5.3_CAD/
The content of pi/Design/Gerber/ is likely an outdated copy of the artwork. I will go through the project and issue a commit that clarifies the situation. In the main time I suggest to keep the fabrication on hold.

**Comment by restelli** [comment]
Closed with commit:  b25263b
